//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace AEP.HQAMC.Branding.ControlTemplates.AEP.HQAMC.GlobalNav {
    
    
    public partial class AEPHQAMCKeyboardMenu2 {
        
        /// <summary>
        /// AEP_HQAMC_GlobalNavContainer2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label AEP_HQAMC_GlobalNavContainer2;
    }
}
