//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Custom.SP2013.GlobalNav.ControlTemplates.Custom.SP2013.GlobalNav {
    
    
    public partial class Custom {
        
        /// <summary>
        /// Custom_SP2013_GlobalNavContainer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label Custom_SP2013_GlobalNavContainer;
    }
}
