//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SP2013.Custom.Branding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomBranding {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomBranding() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SP2013.Custom.Branding.CustomBranding", typeof(CustomBranding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/masterpage/seattle.master.
        /// </summary>
        internal static string BrandingHelper_RemoveComposedLookTopSite__catalogs_masterpage_seattle_master {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveComposedLookTopSite__catalogs_masterpage_seattle_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/fontscheme002.spfont.
        /// </summary>
        internal static string BrandingHelper_RemoveComposedLookTopSite__catalogs_theme_15_fontscheme002_spfont {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveComposedLookTopSite__catalogs_theme_15_fontscheme002_spfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/palette001.spcolor.
        /// </summary>
        internal static string BrandingHelper_RemoveComposedLookTopSite__catalogs_theme_15_palette001_spcolor {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveComposedLookTopSite__catalogs_theme_15_palette001_spcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _layouts/15/images/siteicon.png.
        /// </summary>
        internal static string BrandingHelper_RemoveComposedLookTopSite__layouts_15_images_siteicon_png {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveComposedLookTopSite__layouts_15_images_siteicon_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013Custom/Custom.css.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_Custom_css {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_Custom_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013Custom/customHeader.png.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_CustomHeader_png {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_CustomHeader_" +
                        "png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013Custom/CustomHideNav.css.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_CustomHideNav_css {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_CustomHideNav" +
                        "_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013Custom/logo.png.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_logo_png {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_logo_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013Custom.preview.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_preview {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013_preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/SP2013CustomSiteNav.preview.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013SiteNav_preview {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_masterpage_Custom_SP2013SiteNav_previe" +
                        "w", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/theme/15/SP2013Custom.spcolor.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage___catalogs_theme_15_Custom_spcolor {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage___catalogs_theme_15_Custom_spcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013Custom.master.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage_Custom_SP2013_master {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage_Custom_SP2013_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013CustomSiteNav.master.
        /// </summary>
        internal static string BrandingHelper_RemoveMasterPage_Custom_SP2013CustomSiteNav_master {
            get {
                return ResourceManager.GetString("BrandingHelper_RemoveMasterPage_Custom_SP2013CustomSiteNav_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/masterpage/.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_catalogMasterPage__catalogs_masterpage_ {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_catalogMasterPage__catalogs_masterpage_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom_SP2013_ComposedLook.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_customLookCustom_Custom_SP2013_ComposedLook {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_customLookCustom_Custom_SP2013_ComposedLoo" +
                        "k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/SP2013Custom.spcolor.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_FeatureActivated__catalogs_theme_15_CustomLOGO_spcolor {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_FeatureActivated__catalogs_theme_15_Custom" +
                        "LOGO_spcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/fontscheme002.spfont.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_FeatureActivated__catalogs_theme_15_fontscheme002_spfont {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_FeatureActivated__catalogs_theme_15_fontsc" +
                        "heme002_spfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013Custom/logo.png.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_FeatureActivated_Custom_SP2013_LOGO_png {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_FeatureActivated_Custom_SP2013_LOGO_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/__devicechannelmappings.aspx.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_FeatureDeactivating___catalogs_masterpage___devicechannelmappings_aspx {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_FeatureDeactivating___catalogs_masterpage_" +
                        "__devicechannelmappings_aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a32b6912-77e8-459d-ad50-e387c465320f.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_guidProvisionWebTheme_a32b6912_77e8_459d_ad50_e387c465320f {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_guidProvisionWebTheme_a32b6912_77e8_459d_a" +
                        "d50_e387c465320f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013CustomSiteNav.master.
        /// </summary>
        internal static string DeployComposedLookSiteNavEventReceiver_masterPageName_Custom_CustomSiteNav_master {
            get {
                return ResourceManager.GetString("DeployComposedLookSiteNavEventReceiver_masterPageName_Custom_CustomSiteNav_master" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/masterpage/SP2013Custom/logo.png.
        /// </summary>
        internal static string InheritBranding_WebProvisioned__catalogs_masterpage_Custom_SP2013_LOGO_png {
            get {
                return ResourceManager.GetString("InheritBranding_WebProvisioned__catalogs_masterpage_Custom_SP2013_LOGO_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/SP2013Custom.spcolor.
        /// </summary>
        internal static string InheritBranding_WebProvisioned__catalogs_theme_15_Custom_spcolor {
            get {
                return ResourceManager.GetString("InheritBranding_WebProvisioned__catalogs_theme_15_Custom_spcolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _catalogs/theme/15/fontscheme002.spfont.
        /// </summary>
        internal static string InheritBranding_WebProvisioned__catalogs_theme_15_fontscheme002_spfont {
            get {
                return ResourceManager.GetString("InheritBranding_WebProvisioned__catalogs_theme_15_fontscheme002_spfont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom_SP2013_ComposedLook.
        /// </summary>
        internal static string InheritBranding_WebProvisioned_Custom_SP2013_ComposedLook {
            get {
                return ResourceManager.GetString("InheritBranding_WebProvisioned_Custom_SP2013_ComposedLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013Custom/logo.png.
        /// </summary>
        internal static string ProvisionSiteThemeEventReceiver_FeatureActivated_Custom_SP2013_LOGO_png {
            get {
                return ResourceManager.GetString("ProvisionSiteThemeEventReceiver_FeatureActivated_Custom_SP2013_LOGO_png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_catalogs/masterpage/__devicechannelmappings.aspx.
        /// </summary>
        internal static string ProvisionSiteThemeEventReceiver_FeatureDeactivating___catalogs_masterpage___devicechannelmappings_aspx {
            get {
                return ResourceManager.GetString("ProvisionSiteThemeEventReceiver_FeatureDeactivating___catalogs_masterpage___devic" +
                        "echannelmappings_aspx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP2013Custom.master.
        /// </summary>
        internal static string ProvisionSiteThemeEventReceiver_masterPageName_Custom_SP2013_master {
            get {
                return ResourceManager.GetString("ProvisionSiteThemeEventReceiver_masterPageName_Custom_SP2013_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custom Global Navigation has encountered a problem with a missing Term Store. Please contact your site administrator..
        /// </summary>
        internal static string TermError {
            get {
                return ResourceManager.GetString("TermError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Custom Global Navigation has encountered a problem with a service application. Please contact your site administrator..
        /// </summary>
        internal static string TermServiceAppError {
            get {
                return ResourceManager.GetString("TermServiceAppError", resourceCulture);
            }
        }
    }
}
